### ISSUE TITLE
com.yandex.div.json.ParsingException: Value for key 'log_id' is missing

### ISSUE THREAD

**Issue by LeafyLappa** [divkit/divkit#16]
I keep getting this exception trying to call the constructor of DivData (inside the function parsePayload in the code). Am I doing something wrong here?

```Kotlin
        com.yandex.div.json.ParsingException: Value for key 'log_id' is missing
         at com.yandex.div.json.ParsingExceptionKt.missingValue(ParsingException.kt:17)
         at com.yandex.div.json.JsonParser.read(JsonParser.java:432)
         at com.yandex.div.json.JsonParser.read(JsonParser.java:354)
         at com.yandex.div2.DivData$Companion.fromJson(DivData.kt:50)
         at me.greentail.test.DivkitIntegration.parsePayload(DivkitIntegration.kt:52)
         at me.greentail.test.ui.adapter.delegate.DivkitCardAdapterDelegate$divkitCardAdapterDelegate$2$2.invoke(DivkitCardAdapterDelegate.kt:31)
         at me.greentail.test.ui.adapter.delegate.DivkitCardAdapterDelegate$divkitCardAdapterDelegate$2$2.invoke(DivkitCardAdapterDelegate.kt:30)
         at com.hannesdorfmann.adapterdelegates4.dsl.DslLayoutContainerListAdapterDelegate.onBindViewHolder(LayoutContainerListAdapterDelegateDsl.kt:81)
         at com.hannesdorfmann.adapterdelegates4.dsl.DslLayoutContainerListAdapterDelegate.onBindViewHolder(LayoutContainerListAdapterDelegateDsl.kt:57)
         at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:53)
         at com.hannesdorfmann.adapterdelegates4.AbsListItemAdapterDelegate.onBindViewHolder(AbsListItemAdapterDelegate.java:42)
         at com.hannesdorfmann.adapterdelegates4.AdapterDelegatesManager.onBindViewHolder(AdapterDelegatesManager.java:299)
         at com.hannesdorfmann.adapterdelegates4.AsyncListDifferDelegationAdapter.onBindViewHolder(AsyncListDifferDelegationAdapter.java:127)
         at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
         at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
         at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
         at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
         at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
         at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
         at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
         at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
         at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
         at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
         at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
         at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
         at android.view.View.layout(View.java:22131)
         at android.view.ViewGroup.layout(ViewGroup.java:6438)
         at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
         at android.view.View.layout(View.java:22131)
         at android.view.ViewGroup.layout(ViewGroup.java:6438)
         at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
         at android.view.View.layout(View.java:22131)
         at android.view.ViewGroup.layout(ViewGroup.java:6438)
         at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
         at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
         at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2253)
         at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:953)
         at android.view.View.layout(View.java:22131)
         at android.view.ViewGroup.layout(ViewGroup.java:6438)
         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
         at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
         at android.view.View.layout(View.java:22131)
         at android.view.ViewGroup.layout(ViewGroup.java:6438)
         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
```

Codes

```Kotlin
object DivkitIntegration {
    val gson = Gson()

    fun divConfiguration(context: Context, activity: Activity): DivConfiguration.Builder {
        return DivConfiguration.Builder(ImageLoader(context))
            .enableVisibilityBeacons()
            .enableLongtapActionsPassingToChild()
            .tooltipRestrictor { _, _ -> true }
            .divDownloader(DemoDivDownloader())
            .supportHyphenation(true)
            .visualErrorsEnabled(true)
    }

    fun parsePayload(jsonPayload: String): DivData {
        val data = JSONObject(jsonPayload)
        val env = DivParsingEnvironment(ParsingErrorLogger.LOG)
        return DivData(env, data)
    }

    class ImageLoader(context: Context) : DivImageLoader {
        override fun loadImage(imageUrl: String, callback: DivImageDownloadCallback) = LoadReference {}

        override fun loadImage(imageUrl: String, imageView: ImageView) = LoadReference {}

        override fun loadImageBytes(imageUrl: String, callback: DivImageDownloadCallback) = LoadReference {}
    }

    class DemoDivDownloader : DivDownloader {

        override fun downloadPatch(divView: Div2View, downloadUrl: String, callback: DivPatchDownloadCallback): LoadReference {
            val job = GlobalScope.launch(Dispatchers.Main) {
                callback.onFail()
            }
            return LoadReference {
                job.cancel("cancel all downloads")
            }
        }
    }
}
```

```Kotlin
object DivkitCardAdapterDelegate {

    fun getDivkitView(context: Context): View {
        val contextWrapper = ContextThemeWrapper(context, context.theme)
        return Div2View(Div2Context(contextWrapper, DivkitIntegration.divConfiguration(context, context.activity!!).build()))
    }

    internal fun divkitCardAdapterDelegate(): AdapterDelegate<List<ICardItem>> =
        adapterDelegateView<DivkitCarItem, ICardItem>(::getDivkitView) {
            bind {
                val data = DivkitIntegration.parsePayload(item.divkitPayload)
                (itemView as Div2View).setData(data, DivDataTag("divkit_tag_123"))
            }
        }
}
```

Json

```json
{
    "card": {
        "log_id": "sample_card",
        "states": [
            {
                "state_id": 0,
                "div": {
                    "type": "container",
                    "orientation": "vertical",
                    "margins": {
                        "top": 24,
                        "bottom": 24
                    },
                    "items": [
                        {
                            "type": "container",
                            "orientation": "vertical",
                            "margins": {
                                "bottom": 12
                            },
                            "items": [
                                {
                                    "type": "image",
                                    "height": {
                                        "type": "fixed",
                                        "value": 200
                                    },
                                    "image_url": "https://yastatic.net/s3/home/yandex-app/div_demo/containers.png"
                                },
                                {
                                    "type": "image",
                                    "height": {
                                        "type": "fixed",
                                        "value": 200
                                    },
                                    "alpha": 0.5,
                                    "image_url": "https://yastatic.net/s3/home/yandex-app/div_demo/containers.png"
                                }
                            ]
                        }
                    ]
                }
            }
        ]
    }
}
```

**Comment by divkit** [comment]
You should replace to this:
```
fun parsePayload(jsonPayload: String): DivData {
        val data = JSONObject(jsonPayload)
        val env = DivParsingEnvironment(ParsingErrorLogger.LOG)
        return DivData(env, data.getJSONObject("card"))
    }

**Comment by LeafyLappa** [comment]
I still get the same exception. I can get the value of "log_id" in the debugger though

<img width="775" alt="Screenshot 2023-02-14 at 1 26 45 PM" src="https://user-images.githubusercontent.com/31704619/218708789-2836104f-0f49-4fc0-884e-3952456ddf48.png">

**Comment by LeafyLappa** [comment]
Not sure what I did but it works now. Thank you
