### ISSUE TITLE
Getting issue :                                                                                                     java.lang.NoSuchFieldError: No static field listPopupWindowStyle of type I in class Lcom/yandex/div/R$attr; or its superclasses (declaration of 'com.yandex.div.R$attr' appears in /data/app/com.tokopedia.tkpd-IDj84M0I7f-d4y5tvmWhPg==/base.apk!classes19.dex)

### ISSUE THREAD

**Issue by varun0922** [divkit/divkit#34]
Hi guys I am getting this crash some times while scrolling and loading the components. 
Can you help identify the reason ? 

Stack trace : 

FATAL EXCEPTION: ViewPoolThread
                                                                                                    Process: com.tokopedia.tkpd, PID: 14190
                                                                                                    java.lang.NoSuchFieldError: No static field listPopupWindowStyle of type I in class Lcom/yandex/div/R$attr; or its superclasses (declaration of 'com.yandex.div.R$attr' appears in /data/app/com.tokopedia.tkpd-IDj84M0I7f-d4y5tvmWhPg==/base.apk!classes19.dex)
                                                                                                    	at com.yandex.div.internal.widget.SelectView$PopupWindow.<init>(SelectView.kt:91)
                                                                                                    	at com.yandex.div.internal.widget.SelectView.<init>(SelectView.kt:34)
                                                                                                    	at com.yandex.div.core.view2.divs.widgets.DivSelectView.<init>(DivSelectView.kt:15)
                                                                                                    	at com.yandex.div.core.view2.DivViewCreator.lambda-18$lambda-17$lambda-15(DivViewCreator.kt:66)
                                                                                                    	at com.yandex.div.core.view2.DivViewCreator.$r8$lambda$K0SPGPC2Ad7KsxuvG2cgeoYgIvo(Unknown Source:0)
                                                                                                    	at com.yandex.div.core.view2.DivViewCreator$$ExternalSyntheticLambda13.createView(Unknown Source:2)
                                                                                                    	at com.yandex.div.internal.viewpool.AdvanceViewPool$Channel.createAndEnqueueView(AdvanceViewPool.kt:121)
                                                                                                    	at com.yandex.div.internal.viewpool.ViewCreator$CreateViewTask.run(ViewCreator.kt:89)
                                                                                                    	at com.yandex.div.internal.viewpool.ViewCreator$ViewCreatorThread.createView(ViewCreator.kt:77)
                                                                                                    	at com.yandex.div.internal.viewpool.ViewCreator$ViewCreatorThread.run(ViewCreator.kt:54)

**Comment by divkit** [comment]
Hi! Will look at this

**Comment by varun0922** [comment]
Thanks a lot 👍

**Comment by varun0922** [comment]
I am using these dependencies

**Comment by varun0922** [comment]
Hey guys any findings on this issue :)

**Comment by perforators** [comment]
Possible recommendations to solve the problem:
- Make sure that an attribute named listPopupWindowStyle is not defined in application modules (it may override an attribute from the R class created for DivKit).
- If Proguard/R8 is enabled, try disabling it and testing the application.

**Comment by vyaivanove** [comment]
Closing the issue for now. 
Please let us know if the problem persists even after following the recommendations. In addition to this, try updating Android Gradle Plugin, which will also update R8 version.
